;;; early-init.el --- Emacs early initialization -*- lexical-binding: t; -*-

;; This set folders where the configuration is located
;;     packages: emacs packages configurations
;;     custom: my custom packages (with configuration)
(mapc
    (lambda (string)
        (add-to-list 'load-path (locate-user-emacs-file string)))
        '("./packages" "./custom"))

;; Include custom variables definition to use throughout the configuration process
(require 'custom-vars)

;; Sort autogenerated files 
(require 'sort-autogen)

;; Startup improvements
; This set optimal values for startup
(setq gc-cons-threshold most-positive-fixnum
      gc-cons-percentage 0.5
      file-name-handler-alist nil
      vc-handled-backends nil)

; This will rollback values emacs usage performance
(add-hook 'emacs-startup-hook
  (lambda()
    (setq gc-cons-threshold xap/const/gc-cons-threshold
          gc-cons-percentage xap/const/gc-cons-percentage
          file-name-handler-alist xap/const/file-name-handler-alist
          vc-handled-backends xap/const/vc-handled-backends
          read-process-output-max xap/const/read-process-output)))

;; Base visual configuration
(setq inhibit-startup-message       t
      frame-resize-pixelwise        t
      use-short-answers             t
      frame-inhibit-implied-resize  'force
      package-native-compile        t
      inhibit-default-init         t
      site-run-file                 nil)
(scroll-bar-mode -1)                ; disable scrollbar
(tool-bar-mode -1)                  ; disable toolbar
(tooltip-mode -1)                   ; disable tooltips
(set-fringe-mode 10)                ; give some breathing room
(menu-bar-mode -1)                  ; disable menubar
(blink-cursor-mode 0)               ; disable blinking cursor
(set-face-background 'default xap/const/initial-background-color)
(set-face-foreground 'default xap/const/initial-foreground-color)

;; Disable package.el to comply with elpaca
(setq package-enable-at-startup nil)

;;; early-init.el ends here.

